name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Set up jsonnet & jsonnet-bundler
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
      - name: Install dependencies
        run: npm install
      - name: Snapshot Testing
        run: npm run test
